#!/usr/bin/env bash
set -euo pipefail

echo "--- WallSet Debug ---"

LAST_WALL="$HOME/.config/hyprpaper/SelectedWallpaper.png"

# --- Select wallpaper ---
if [ $# -gt 0 ] && [ -f "$1" ]; then
    wallpaper="$1"
    echo "Using wallpaper from argument: $wallpaper"
elif [ -f "$LAST_WALL" ]; then
    wallpaper="$LAST_WALL"
    echo "Using last selected wallpaper: $wallpaper"
elif [ -d "$HOME/Pictures/Wallpapers" ]; then
    wallpaper=$(find "$HOME/Pictures/Wallpapers" -type f | shuf -n1)
    echo "Using random wallpaper: $wallpaper"
else
    wallpaper="$HOME/.config/ags/assets/default_wallpaper"
    echo "Using fallback wallpaper: $wallpaper"
fi
wallpaper=$(echo "$wallpaper" | xargs)  # trim whitespace

# --- Save for next time ---
mkdir -p "$(dirname "$LAST_WALL")"
cp "$wallpaper" "$LAST_WALL"

# --- Average color ---
echo "Calculating average color..."
avg_rgb=$(magick "$wallpaper" -scale 1x1! -format "%[fx:int(255*r)] %[fx:int(255*g)] %[fx:int(255*b)]" info:)
avg_r=$(echo "$avg_rgb" | cut -d' ' -f1)
avg_g=$(echo "$avg_rgb" | cut -d' ' -f2)
avg_b=$(echo "$avg_rgb" | cut -d' ' -f3)
echo "Average RGB: R=$avg_r, G=$avg_g, B=$avg_b"

# --- Brightness & mode ---
brightness=$(( (avg_r*299 + avg_g*587 + avg_b*114)/1000 ))
mode=$([ "$brightness" -gt 128 ] && echo light || echo dark)
echo "Perceived brightness: $brightness, Mode: $mode"

# --- Chroma & scheme ---
max_rgb=$((avg_r>avg_g?(avg_r>avg_b?avg_r:avg_b):(avg_g>avg_b?avg_g:avg_b)))
min_rgb=$((avg_r<avg_g?(avg_r<avg_b?avg_r:avg_b):(avg_g<avg_b?avg_g:avg_b)))
chroma=$((max_rgb - min_rgb))
scheme=$([ "$chroma" -lt 50 ] && echo scheme-neutral || echo scheme-rainbow)
echo "Chroma: $chroma, Scheme: $scheme"

# --- Write Matugen variables ---
matugen_file="$HOME/.config/ags/style/abstracts/_theme_variables_matugen.scss"
{
    echo "/* Generated by WallSet */"
    echo "\$darkmode: $([ "$mode" = dark ] && echo true || echo false);"
    echo "\$material-color-scheme: \"$scheme\";"
    echo "\$wall_r: $avg_r;"
    echo "\$wall_g: $avg_g;"
    echo "\$wall_b: $avg_b;"
} > "$matugen_file"
echo "Matugen variables written to $matugen_file"

# --- Apply wallpaper ---
echo "Applying wallpaper..."
hyprctl hyprpaper preload "$wallpaper"
for mon in $(hyprctl monitors | awk '/Monitor/ {print $2}'); do
    hyprctl hyprpaper wallpaper "$mon,$wallpaper"
    echo "Wallpaper set for monitor $mon"
done

# --- Regenerate Matugen theme ---
echo "Regenerating Matugen theme..."
matugen -t "$scheme" -m "$mode" image "$wallpaper"

# --- Notification ---
if command -v notify-send &>/dev/null; then
    notify-send "Chromash" \
        "Wallpaper: $(basename "$wallpaper")\nMode: $mode\nScheme: $scheme" \
        -u normal \
        -i "${LAST_WALL}" \
        -t 3000
fi


echo "DONE! Mode=$mode, Scheme=$scheme"
